services:
  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    restart: unless-stopped
    pid: host # let the container see the host's PID's 
    network_mode: host # lets glances see the host's network stats
    environment:
      - GLANCES_OPT=-w # enable web interface
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/host:ro # allows host filesystem metrics

# docker compose up -d
# http://localhost:61208
# http://<your-pc-ip>:61208


##################
# Windows Config #
##################

services:
  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    restart: unless-stopped
    ports:
      - "61208:61208"
    environment:
      - GLANCES_OPT=-w
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro