apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  namespace: mynamespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers: 
        - name: nginx-container
          image: nginx

# kubectl create -f deployment.yaml
# kubectl get deployments -n mynamespace
# kubectl get pods -n mynamespace