apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-deployment
  template:
    metadata:
      labels:
        app: myapp-deployment
    spec: 
      containers:
        - name: myapp-container
          image: nginx:latest
          ports:
            - containerPort: 80

# kubectl apply -f myapp-deploymnet.yaml
# kubectl get deployments -n default
# kubectl get pods
# kubectl describe deployment myapp-deployment