apiVersion: v1
kind: Service 
metadata:
  name: myapp-service
spec:
  selector:
    name: myapp-deployment
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 80

# kubectl apply -f myapp-service.yaml
# kubectl get svc -n default
# kubectl describe svc myapp-service