apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: mynamespace
type: Opaque
data:
  username: cwdffffewf
  password: fwefef

# kubectl create -f secrets.yaml
# kubectl get secrets -n mynamespace
# kubectl describe secret mysecret -n mynamespace