services:
  uptime_kuma:
    image: louislam/uptime-kuma:latest 
    container_name: uptime_kuma
    ports:
      - "3001:3001"
    volumes:
      - kuma_data:/app/data 
    restart: unless-stopped 

volumes:
  kuma_data:
