services:
  socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: tugtainer-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    read_only: true
    environment:
      - CONTAINERS=1
      - IMAGES=1
      - NETWORKS=1
      - VOLUMES=1
      - POST=1
    networks:
      - tugtainer_net
    restart: unless-stopped
    ports:
      - 2375:2375
    tmpfs:
      - /run

  app:
    image: ghcr.io/quenary/tugtainer:1
    container_name: tugtainer
    volumes:
      - tugtainer_data:/tugtainer
    environment:
      - DOCKER_HOST=tcp://tugtainer-socket-proxy:2375
    ports:
      - "9412:80"
    depends_on:
      - socket-proxy
    networks:
      - tugtainer_net
    restart: unless-stopped

networks:
  tugtainer_net:
    driver: bridge

volumes:
  tugtainer_data:
