apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: redis
  name: redis
spec:
  contianers:
  - image: redis123
    name: redis
    resource: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

#kubectl create -f redis-definition.yaml 
#kubectl get pods
