version: "3.8"

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - "3003:3000"
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=*
    volumes:
      - ./config:/app/config
    restart: unless-stopped

# When deploying it with coolify ports are not needed 
# Configure the subdomain and the name you want so http://subdomain:80 
# in the coolify setup page in the services section click on setting and paster the url in there
# deploy the container once complete
